branch 1.0

diff --git a/.github/workflows/docs_test.yml b/.github/workflows/docs_test.yml
--- a/.github/workflows/docs_test.yml
+++ b/.github/workflows/docs_test.yml
@@ -1,3 +1,5 @@
+---
+
 name: Docs Tests
 
 on:
@@ -20,7 +22,19 @@ on:
 
 jobs:
   test-examples:
-    name: Run Examples
+    strategy:
+      fail-fast: false
+      matrix:
+        php-version:
+          - "7.3"
+          - "7.4"
+          - "8.1"
+          - "8.2"
+        dependencies:
+          - lowest
+          - highest
+
+    name: Run Examples (PHP-${{ matrix.php-version }}:${{ matrix.dependencies }})
 
     runs-on: ubuntu-latest
 
@@ -28,10 +42,17 @@ jobs:
       - uses: actions/checkout@v3
       - uses: shivammathur/setup-php@v2
         with:
-          php-version: "8.1"
+          php-version: ${{ matrix.php-version }}
           coverage: none
 
-      - run: composer update --no-interaction --no-progress --ansi
+      - if: matrix.dependencies == 'highest'
+        run: composer update --no-interaction --no-progress --ansi
+
+      - if: matrix.dependencies == 'lowest'
+        run: composer update --no-interaction --no-progress --ansi --prefer-lowest
+
+      - run: "(outdir=\"`docs/sphinx/behat/get-output-path`\"; if [ ! -d \"$outdir\" ]; then echo \"error: directory '$outdir' does not exist\" >&2; exit 1; fi)"
+
       - run: composer bin behat update --no-interaction --no-progress --ansi
 
       - run: vendor-bin/behat/vendor/bin/behat -c docs/behat.yml
@@ -46,7 +67,7 @@ jobs:
       - uses: actions/checkout@v3
       - uses: shivammathur/setup-php@v2
         with:
-          php-version: "8.1"
+          php-version: "8.2"
           coverage: none
 
       - name: Initialize Docker environment
